version: '3'
services: 
  ZJUauth-gRPC:
    image: ${IMAGE_TAG}-${CI_COMMIT_SHA}
    networks:
      - traefik_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.tags=grpc"
        - "traefik.port=50053"
        - "traefik.protocol=h2c"
        - "traefik.docker.network=traefik_net"
        - "traefik.backend=ZJUauth-gRPC"
        - "traefik.frontend.rule=PathPrefix:/qscrpc.ZJUauth/"

networks:
  traefik_net:
    external: true